import type { DemoSiteConfig } from './demo-site.types';

export const DEMO_SITES = {
  saas: {
    id: 'saas',
    name: 'CloudForge',
    tagline: 'Identity & workspace platform',
    domain: 'SaaS',
    theme: 'dark',
    fx: 'holo',
    accent: '#a78bfa',
    route: '/saas',
    description: 'Team directory, access control, and workspace administration.',
  },
  commerce: {
    id: 'commerce',
    name: 'ShopWave',
    tagline: 'Commerce operations hub',
    domain: 'E-Commerce',
    theme: 'light',
    fx: 'glass',
    accent: '#f97316',
    route: '/commerce',
    description: 'Product catalog, orders, and storefront analytics.',
  },
  fintech: {
    id: 'fintech',
    name: 'CapitalFlow',
    tagline: 'Wealth & portfolio management',
    domain: 'FinTech',
    theme: 'dark',
    fx: 'neon',
    accent: '#22d3ee',
    route: '/fintech',
    description: 'Portfolio performance, approvals, and market insights.',
  },
  healthcare: {
    id: 'healthcare',
    name: 'VitaCare',
    tagline: 'Patient-centered care portal',
    domain: 'Healthcare',
    theme: 'light',
    fx: null,
    accent: '#10b981',
    route: '/healthcare',
    description: 'Intake forms, care plans, and clinical timelines.',
  },
  education: {
    id: 'education',
    name: 'LearnHub',
    tagline: 'Learning management system',
    domain: 'Education',
    theme: 'light',
    fx: 'holo',
    accent: '#6366f1',
    route: '/education',
    description: 'Course structure, assignments, and learner progress.',
  },
  cyber: {
    id: 'cyber',
    name: 'CyberNexus',
    tagline: 'Security operations center',
    domain: 'Cybersecurity',
    theme: 'dark',
    fx: 'cyber',
    accent: '#00ffaa',
    route: '/cyber',
    description: 'Threat monitoring, neural pipelines, and incident response.',
  },
} as const satisfies Record<string, DemoSiteConfig>;

export const DEMO_SITE_LIST: DemoSiteConfig[] = [
  DEMO_SITES.saas,
  DEMO_SITES.commerce,
  DEMO_SITES.fintech,
  DEMO_SITES.healthcare,
  DEMO_SITES.education,
  DEMO_SITES.cyber,
];
